import { MigrationInterface, QueryRunner } from "typeorm";

export class FirstMigration1765520674710 implements MigrationInterface {
    name = 'FirstMigration1765520674710'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`location_master\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`type\` enum ('country', 'state', 'city') NOT NULL, \`value\` varchar(255) NOT NULL, \`status\` enum ('active', 'inactive') NOT NULL DEFAULT 'active', \`is_deleted\` tinyint NOT NULL DEFAULT 0, \`parent_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`organizations\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`level\` int NOT NULL DEFAULT '0', \`legal_name\` varchar(255) NOT NULL, \`trade_name\` varchar(255) NOT NULL, \`customer_type\` varchar(255) NOT NULL, \`msa_number\` varchar(255) NOT NULL, \`organization_type\` varchar(255) NOT NULL, \`business_registration_number\` varchar(255) NOT NULL, \`address_line\` varchar(255) NOT NULL, \`status\` enum ('active', 'inactive') NOT NULL DEFAULT 'active', \`activated_at\` timestamp NULL, \`serviceRegions\` text NULL, \`parent_id\` varchar(36) NULL, \`root_id\` varchar(36) NULL, \`country_id\` varchar(36) NULL, \`state_id\` varchar(36) NULL, \`city_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_mfa\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`method\` varchar(255) NOT NULL, \`user_id\` varchar(36) NULL, UNIQUE INDEX \`REL_a3db12d521d7b1f7d17c71e465\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`device_info\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`ip_address\` varchar(255) NOT NULL, \`device_type\` varchar(255) NOT NULL, \`os_type\` varchar(255) NOT NULL, \`browser\` varchar(255) NOT NULL, \`location\` varchar(255) NULL, \`latitude\` double NULL, \`longitude\` double NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_session\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`status\` enum ('active', 'inactive') NOT NULL DEFAULT 'active', \`is_current\` tinyint NOT NULL, \`last_activity\` timestamp NOT NULL, \`revoked_at\` timestamp NULL, \`user_id\` varchar(36) NULL, \`device_info_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`otp\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`type\` enum ('mobile', 'email') NOT NULL, \`value\` varchar(255) NOT NULL, \`code\` varchar(255) NOT NULL, \`expires_at\` timestamp NOT NULL, \`is_used\` tinyint NOT NULL, \`user_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`password_history\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`password_hash\` varchar(255) NOT NULL, \`is_current\` tinyint NOT NULL, \`expired_at\` timestamp NULL, \`user_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`password_reset_token\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`token\` varchar(255) NOT NULL, \`expires_at\` timestamp NOT NULL, \`is_used\` tinyint NOT NULL, \`user_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_activity_log\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`event_type\` varchar(255) NOT NULL, \`event_description\` varchar(255) NOT NULL, \`user_id\` varchar(36) NULL, \`device_info_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_notification_log\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`title\` varchar(255) NOT NULL, \`message\` varchar(255) NOT NULL, \`event_type\` varchar(255) NOT NULL, \`is_read\` tinyint NOT NULL, \`user_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_notification_settings\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`email_system_alerts\` tinyint NOT NULL, \`email_plan_changes\` tinyint NOT NULL, \`email_usage_alerts\` tinyint NOT NULL, \`email_security_alerts\` tinyint NOT NULL, \`email_newsletter\` tinyint NOT NULL, \`push_system_alerts\` tinyint NOT NULL, \`push_plan_changes\` tinyint NOT NULL, \`push_usage_alerts\` tinyint NOT NULL, \`push_security_alerts\` tinyint NOT NULL, \`sms_critical_alerts\` tinyint NOT NULL, \`sms_security_alerts\` tinyint NOT NULL, \`user_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_login_attempts\` (\`id\` varchar(36) NOT NULL, \`user_id\` varchar(255) NOT NULL, \`failed_attempts\` int NOT NULL DEFAULT '0', \`locked_until\` timestamp NULL, \`last_attempt_at\` timestamp NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`role_name\` varchar(255) NOT NULL, \`role_description\` varchar(255) NOT NULL, \`status\` enum ('active', 'inactive') NOT NULL DEFAULT 'active', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`username\` varchar(150) NOT NULL DEFAULT '', \`email\` varchar(200) NOT NULL, \`full_name\` varchar(150) NULL, \`phone\` varchar(20) NULL, \`country_code\` varchar(10) NULL, \`title\` varchar(50) NULL, \`status\` enum ('active', 'inactive') NOT NULL, \`profile_image_url\` varchar(255) NULL, \`language_preference_id\` varchar(255) NULL, \`mfa_enabled\` tinyint NOT NULL DEFAULT 0, \`is_strong_password\` tinyint NOT NULL DEFAULT 0, \`is_telesat_user\` tinyint NOT NULL DEFAULT 0, \`mfa_secret\` varchar(255) NULL, \`role_id\` varchar(36) NULL, \`organization_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_permission\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`subOrg\` text NOT NULL, \`logs\` text NOT NULL, \`users\` text NOT NULL, \`roles\` text NOT NULL, \`user_id\` varchar(36) NULL, UNIQUE INDEX \`REL_2305dfa7330dd7f8e211f4f35d\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_org_mapping\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`is_sub_org_admin\` tinyint NOT NULL DEFAULT 0, \`user_id\` varchar(36) NULL, \`organization_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_group\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`name\` varchar(150) NOT NULL, \`description\` varchar(250) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_group_mapping\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`user_id\` varchar(36) NULL, \`group_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_role_mapping\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`status\` enum ('active', 'inactive') NOT NULL DEFAULT 'active', \`user_id\` varchar(36) NULL, \`role_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`permission_module\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`module_name\` varchar(255) NOT NULL, \`role_id\` varchar(255) NOT NULL, \`user_id\` varchar(255) NOT NULL, \`action\` enum ('create', 'read', 'update', 'delete') NOT NULL, \`status\` enum ('active', 'inactive') NOT NULL DEFAULT 'active', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`location_master\` ADD CONSTRAINT \`FK_15a1c729de850db3a05f46a5b0a\` FOREIGN KEY (\`parent_id\`) REFERENCES \`location_master\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organizations\` ADD CONSTRAINT \`FK_f3a7c9411eaa5f9cbc5363de331\` FOREIGN KEY (\`parent_id\`) REFERENCES \`organizations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organizations\` ADD CONSTRAINT \`FK_a44af4ad29fa40a0b4555a55c39\` FOREIGN KEY (\`root_id\`) REFERENCES \`organizations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organizations\` ADD CONSTRAINT \`FK_c2352a5aaf5ace8fde679a8d95c\` FOREIGN KEY (\`country_id\`) REFERENCES \`location_master\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organizations\` ADD CONSTRAINT \`FK_e1a306c70085ef93720d015f9c3\` FOREIGN KEY (\`state_id\`) REFERENCES \`location_master\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organizations\` ADD CONSTRAINT \`FK_d0622ba0d9f7901c7469f4ac9d2\` FOREIGN KEY (\`city_id\`) REFERENCES \`location_master\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_mfa\` ADD CONSTRAINT \`FK_a3db12d521d7b1f7d17c71e465a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_session\` ADD CONSTRAINT \`FK_13275383dcdf095ee29f2b3455a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_session\` ADD CONSTRAINT \`FK_6a73c1e72eccfbc2b49cd9ea62e\` FOREIGN KEY (\`device_info_id\`) REFERENCES \`device_info\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`otp\` ADD CONSTRAINT \`FK_258d028d322ea3b856bf9f12f25\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`password_history\` ADD CONSTRAINT \`FK_4933dc7a01356ac0733a5ad52d9\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`password_reset_token\` ADD CONSTRAINT \`FK_7eabb22ed38459ffc24dc8b415d\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_activity_log\` ADD CONSTRAINT \`FK_183f150706f5153047a1ef4b890\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_activity_log\` ADD CONSTRAINT \`FK_89a68e302c8b2d40d7a55f0520f\` FOREIGN KEY (\`device_info_id\`) REFERENCES \`device_info\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_notification_log\` ADD CONSTRAINT \`FK_40b9e7012242f6c70b68180695a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_notification_settings\` ADD CONSTRAINT \`FK_52182ffd0f785e8256f8fcb4fd6\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_login_attempts\` ADD CONSTRAINT \`FK_cd1fbfdad5747082951d081cbbf\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_a2cecd1a3531c0b041e29ba46e1\` FOREIGN KEY (\`role_id\`) REFERENCES \`role\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_21a659804ed7bf61eb91688dea7\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organizations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_permission\` ADD CONSTRAINT \`FK_2305dfa7330dd7f8e211f4f35d9\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_org_mapping\` ADD CONSTRAINT \`FK_55fbe905eee7139c5d7c0693f34\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_org_mapping\` ADD CONSTRAINT \`FK_01bca303b4db65b8830e0fd58ae\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organizations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_group_mapping\` ADD CONSTRAINT \`FK_e530b8ff61e27bfc247cb8b8bef\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_group_mapping\` ADD CONSTRAINT \`FK_59d3aa3210607a805448579367f\` FOREIGN KEY (\`group_id\`) REFERENCES \`user_group\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role_mapping\` ADD CONSTRAINT \`FK_602e47e915d8f2cb7515e51e64d\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role_mapping\` ADD CONSTRAINT \`FK_35ce72cdd0a4060d0e53629ea3f\` FOREIGN KEY (\`role_id\`) REFERENCES \`role\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_role_mapping\` DROP FOREIGN KEY \`FK_35ce72cdd0a4060d0e53629ea3f\``);
        await queryRunner.query(`ALTER TABLE \`user_role_mapping\` DROP FOREIGN KEY \`FK_602e47e915d8f2cb7515e51e64d\``);
        await queryRunner.query(`ALTER TABLE \`user_group_mapping\` DROP FOREIGN KEY \`FK_59d3aa3210607a805448579367f\``);
        await queryRunner.query(`ALTER TABLE \`user_group_mapping\` DROP FOREIGN KEY \`FK_e530b8ff61e27bfc247cb8b8bef\``);
        await queryRunner.query(`ALTER TABLE \`user_org_mapping\` DROP FOREIGN KEY \`FK_01bca303b4db65b8830e0fd58ae\``);
        await queryRunner.query(`ALTER TABLE \`user_org_mapping\` DROP FOREIGN KEY \`FK_55fbe905eee7139c5d7c0693f34\``);
        await queryRunner.query(`ALTER TABLE \`user_permission\` DROP FOREIGN KEY \`FK_2305dfa7330dd7f8e211f4f35d9\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_21a659804ed7bf61eb91688dea7\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_a2cecd1a3531c0b041e29ba46e1\``);
        await queryRunner.query(`ALTER TABLE \`user_login_attempts\` DROP FOREIGN KEY \`FK_cd1fbfdad5747082951d081cbbf\``);
        await queryRunner.query(`ALTER TABLE \`user_notification_settings\` DROP FOREIGN KEY \`FK_52182ffd0f785e8256f8fcb4fd6\``);
        await queryRunner.query(`ALTER TABLE \`user_notification_log\` DROP FOREIGN KEY \`FK_40b9e7012242f6c70b68180695a\``);
        await queryRunner.query(`ALTER TABLE \`user_activity_log\` DROP FOREIGN KEY \`FK_89a68e302c8b2d40d7a55f0520f\``);
        await queryRunner.query(`ALTER TABLE \`user_activity_log\` DROP FOREIGN KEY \`FK_183f150706f5153047a1ef4b890\``);
        await queryRunner.query(`ALTER TABLE \`password_reset_token\` DROP FOREIGN KEY \`FK_7eabb22ed38459ffc24dc8b415d\``);
        await queryRunner.query(`ALTER TABLE \`password_history\` DROP FOREIGN KEY \`FK_4933dc7a01356ac0733a5ad52d9\``);
        await queryRunner.query(`ALTER TABLE \`otp\` DROP FOREIGN KEY \`FK_258d028d322ea3b856bf9f12f25\``);
        await queryRunner.query(`ALTER TABLE \`user_session\` DROP FOREIGN KEY \`FK_6a73c1e72eccfbc2b49cd9ea62e\``);
        await queryRunner.query(`ALTER TABLE \`user_session\` DROP FOREIGN KEY \`FK_13275383dcdf095ee29f2b3455a\``);
        await queryRunner.query(`ALTER TABLE \`user_mfa\` DROP FOREIGN KEY \`FK_a3db12d521d7b1f7d17c71e465a\``);
        await queryRunner.query(`ALTER TABLE \`organizations\` DROP FOREIGN KEY \`FK_d0622ba0d9f7901c7469f4ac9d2\``);
        await queryRunner.query(`ALTER TABLE \`organizations\` DROP FOREIGN KEY \`FK_e1a306c70085ef93720d015f9c3\``);
        await queryRunner.query(`ALTER TABLE \`organizations\` DROP FOREIGN KEY \`FK_c2352a5aaf5ace8fde679a8d95c\``);
        await queryRunner.query(`ALTER TABLE \`organizations\` DROP FOREIGN KEY \`FK_a44af4ad29fa40a0b4555a55c39\``);
        await queryRunner.query(`ALTER TABLE \`organizations\` DROP FOREIGN KEY \`FK_f3a7c9411eaa5f9cbc5363de331\``);
        await queryRunner.query(`ALTER TABLE \`location_master\` DROP FOREIGN KEY \`FK_15a1c729de850db3a05f46a5b0a\``);
        await queryRunner.query(`DROP TABLE \`permission_module\``);
        await queryRunner.query(`DROP TABLE \`user_role_mapping\``);
        await queryRunner.query(`DROP TABLE \`user_group_mapping\``);
        await queryRunner.query(`DROP TABLE \`user_group\``);
        await queryRunner.query(`DROP TABLE \`user_org_mapping\``);
        await queryRunner.query(`DROP INDEX \`REL_2305dfa7330dd7f8e211f4f35d\` ON \`user_permission\``);
        await queryRunner.query(`DROP TABLE \`user_permission\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`role\``);
        await queryRunner.query(`DROP TABLE \`user_login_attempts\``);
        await queryRunner.query(`DROP TABLE \`user_notification_settings\``);
        await queryRunner.query(`DROP TABLE \`user_notification_log\``);
        await queryRunner.query(`DROP TABLE \`user_activity_log\``);
        await queryRunner.query(`DROP TABLE \`password_reset_token\``);
        await queryRunner.query(`DROP TABLE \`password_history\``);
        await queryRunner.query(`DROP TABLE \`otp\``);
        await queryRunner.query(`DROP TABLE \`user_session\``);
        await queryRunner.query(`DROP TABLE \`device_info\``);
        await queryRunner.query(`DROP INDEX \`REL_a3db12d521d7b1f7d17c71e465\` ON \`user_mfa\``);
        await queryRunner.query(`DROP TABLE \`user_mfa\``);
        await queryRunner.query(`DROP TABLE \`organizations\``);
        await queryRunner.query(`DROP TABLE \`location_master\``);
    }

}
